### ISSUE TITLE
Not working after page reload

### ISSUE THREAD

**Issue by Nordiii** [theripper93/Weather-Blocker#2]
When reloading the page the blocker stops working for me (no error) until I update the polygon.
The same happens if I switch back and forth between scenes.

Foundry: 0.8.6
FXMaster: 1.0.10
Weather Blocker: 0.5
Browser: Firefox

**Comment by theripper93** [comment]
You have probably better roofs and are placing a polygon on top of a better roof. if you have the weather blocker integration enabled in better roofs you don't need to draw polygons for roofs with weather blocker. overlapping zone will cause errors like this due to pixi limitations

**Comment by Nordiii** [comment]
I do not use better roofs yet as I have no maps for this.

The weather blocker works just perfect until reload.

Tested with a new world and only weather blocker and fx master enabled.

**Comment by theripper93** [comment]
do you get the issue only with fxmaster effects or with base foundry weathers as well?

**Comment by Nordiii** [comment]
Didnt know that Foundry hat weather effects as baseline.

I only tested it with FXMaster effects. 
My plan was to use it with Calendar/Weather and FXMaster.

**Comment by theripper93** [comment]
just test with base foundry weather to help isolate the issue please. my guess would be that fx master is not yet initialized when weather blockers applies stuff to the scene

**Comment by Nordiii** [comment]
Okay, tested it with FXMaster disabled and it did work as intended, even after a refresh / scene change.

**Comment by theripper93** [comment]
ok, then i'll have a chat with the fxmaster dev to se if he can call a refresh of my module on his end or if he has a suggestion on when i shoul call it

**Comment by Nordiii** [comment]
Thanks for your time and effort!

**Comment by theripper93** [comment]
they already answered, update coming as soon as fxmaster updates :P

**Comment by vtt-lair** [comment]
@theripper93 just wanted to double check... as I don't want to create another duplicate issue but would this be related to FX Master issue?

I've setup my ship using Better Roofs, Levels, Wall Height and Weather Blocker. As soon as I enable FX Master, the lighting and effects goes all inverted... I guess you can say...

Ship setup with levels and wall heights with Weather Blocker disabled and FX Master enabed:
![image](https://user-images.githubusercontent.com/33215552/122210652-283e5a00-cea6-11eb-89c4-8665962a0047.png)

Same ship with Weather Blocker enabled and FX Master enabled:
![image](https://user-images.githubusercontent.com/33215552/122210782-4d32cd00-cea6-11eb-99de-cef52211de15.png)

As soon as those two are enabled at the same time it does that when you create a stair or when you view from a player's view.

**Comment by theripper93** [comment]
it seems fxmaster added a weather blocking feature as well wich fucks over all my synegrizing module lol. And this is a separate issue yes

**Comment by theripper93** [comment]
are you using perfect vision as well?

**Comment by vtt-lair** [comment]
Usually, but in this case Perfect Vision was off and switching it on without FX Master didn't make a difference.

Only modules on at the time that it happens:

- Better Roofs
- FX Master
- Levels
- libWrapper
- Tidy UI
- Wall Height
- Weather Blocker

Toggling either FX Master or Weather Blocker on fixes the issue, but as soon as both of them are on it causes that.

**Comment by theripper93** [comment]
i can confirm the latest FX master update broke something - if you need it to work right now you can rollback fx master

**Comment by vtt-lair** [comment]
Thanks for the update

**Comment by theripper93** [comment]
try to update weather blocker, should work now!

**Comment by Nordiii** [comment]
Works great (for me) now!

Thanks.
