### ISSUE TITLE
Block Weather works on GM's view but not player's view

### ISSUE THREAD

**Issue by vtt-lair** [theripper93/Weather-Blocker#3]
Foundry: 0.8.7
FXMaster: 1.0.10
Weather Blocker: 0.6.1
Better Roofs: Not installed

Thanks for the awesome module. I was quickly testing this for the lower decks of a ship map. The blockWeather polygon is working 100% on my GM view, however if I log in as a player it does not work:

GM View:
![image](https://user-images.githubusercontent.com/33215552/122099194-06939300-ce12-11eb-911d-56e3c92f25f9.png)

Player View:
![image](https://user-images.githubusercontent.com/33215552/122099222-0d220a80-ce12-11eb-9c52-6fd0f5a293d3.png)

Edit: I noticed after updating the drawing while the player was connected, that it then works as expected. However, a refresh on the player's side (and also on the GM's side) and the weather is no longer blocked.

GM View:
![image](https://user-images.githubusercontent.com/33215552/122099639-8588cb80-ce12-11eb-972f-ab812b563a49.png)

Player View:
![image](https://user-images.githubusercontent.com/33215552/122099622-802b8100-ce12-11eb-90ee-677140542822.png)

A quick double click on GM's side on the drawing and a "Update Drawing" will then have the weather blocked for both GM and player:

GM View:
![image](https://user-images.githubusercontent.com/33215552/122099771-acdf9880-ce12-11eb-918d-8e3db9ca4592.png)

Player View:
![image](https://user-images.githubusercontent.com/33215552/122099753-a6e9b780-ce12-11eb-9ee2-7d751f1e1abe.png)

**Comment by theripper93** [comment]
That is probably the same as the other reported issue, check if the problem persists with basic foundry weathers instead of fix master ones . If the issue doesn’t persist then you’ll have to wait until fxmaster updates for the issue to be fixed

**Comment by vtt-lair** [comment]
Will have a look, thanks

**Comment by theripper93** [comment]
It is possible that for the moment just installing better roofs will solve the issue

**Comment by vtt-lair** [comment]
Tested as per your recommendation and it's definitely FX Master related. Will test separately with Better Roofs as well, but will mark this as closed as it's a duplicate if #2.
