### ISSUE TITLE
Levels module integration?

### ISSUE THREAD

**Issue by Jamo181** [theripper93/Weather-Blocker#6]
Not really an issue more of a suggestion, I'm interested in blocking weather for a certain level range, that are defined in the level module settings.
Maybe this already exists?

A bad ascii house with rain droplets
```
` ` `  ` `   ` `  ` `        <--- open air all the weather effects levels > 30
`` `/¯¯¯¯¯¯\  ` `          <--- walls at levels 20 to 29 blocked by the level / better roofs outline
  ``|_______| `  `         <--- walls at levels 10 to 19 blocked by the level / better roofs outline
 ___|_______|_____       <--- walls at level 0-19 blocked by the level / better roofs outline
```

sorry for my crude example, would this function sit in Weather blocker or would you see it in something else?

Example from a game i'm setting up weather inside hull of ship, think it possible to block it using the walls etc..: 
![image](https://user-images.githubusercontent.com/43423302/156884303-1af00794-0117-4f1c-834e-280d599f36d4.png)

Then the top of the ship would show all the weather effects.
![image](https://user-images.githubusercontent.com/43423302/156884359-c9e82fc8-5bd8-4c9c-8b4c-8a350619888c.png)

**Comment by theripper93** [comment]
Hello! It seems you haven't read the Before Posting an issue as indicated at the top of the Repository Readme (https://github.com/theripper93/Levels/blob/v9/ISSUES.md) The Issue has been closed.
